language: go
go:
- "1.7"
- "1.8"
- "1.9"
- "1.10"
- master
matrix:
  allow_failures:
    - go: master
  fast_finish: true
branches:
  only:
  - master
install:
- go get golang.org/x/net/html
- go get github.com/spf13/cobra
- go get github.com/spf13/pflag
- go get github.com/sirupsen/logrus
- go get github.com/google/go-github/github
- go get github.com/McKael/madonctl/printer/colors
- go get github.com/ghodss/yaml
- go get github.com/pkg/errors
- go get github.com/kr/text
- go get github.com/mattn/go-isatty
